### ISSUE TITLE
Bug: battle tactics vs population

### ISSUE THREAD

**Issue by DCowboy** [YeOldeDM/wangu#16]
If your battle tactics causes your trooper's deaths to cause your population to become lower than 50% your workforce numbers will drop as well which will spam "1 new jobs have opened up. ..." message. 

In my case, auto fight is not allowing my bots to ever reach 100% because they tend to get killed before it gets above 90% but their numbers are almost equal to my workforce. < 100 difference. when they die, it causes the workforce numbers to drop too which means that message gets spammed.

**Comment by DCowboy** [comment]
here's a pic to show what I mean:
![wangu_troopers_breaking_workforce_breaking_news](https://cloud.githubusercontent.com/assets/4471773/11729467/6e7c25d4-9f5d-11e5-896f-ab4b9eb479ce.jpeg)

**Comment by YeOldeDM** [comment]
Related to issue #10 

Closing that issue, since this one is more thorough.

Future development should prevent the player from being able to upgrade Battle Tactics by requiring a minimum max population, or something along those lines.

As a hot-fix, upgrading the Tactics building can require a check on max population, and throw a news message up if it fails.

**Comment by YeOldeDM** [comment]
I think this muther has finally been smashed. Well enough, at least.

A check in the population script will detect an overflow of workers, and initiate a Strike; all workers will leave their jobs and the player will have to re-assign all workers.
I'm calling this closed.
